// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Web50cawSMo8bfb0bPJr2ajeyEfgO74',
    appId: '1:19406723565:web:f227fa7c60d388e5f4afe4',
    messagingSenderId: '19406723565',
    projectId: 'sos-community-app',
    authDomain: 'sos-community-app.firebaseapp.com',
    databaseURL: 'https://sos-community-app-default-rtdb.firebaseio.com',
    storageBucket: 'sos-community-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ygJbh_AZdnA412nGJinHkEOPJuO1lW4',
    appId: '1:19406723565:android:258511218f5ddf70f4afe4',
    messagingSenderId: '19406723565',
    projectId: 'sos-community-app',
    databaseURL: 'https://sos-community-app-default-rtdb.firebaseio.com',
    storageBucket: 'sos-community-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcCyh5DCKEGHmMpP-hxgtfsrJVtNtpw8A',
    appId: '1:19406723565:ios:41c663a15846f034f4afe4',
    messagingSenderId: '19406723565',
    projectId: 'sos-community-app',
    databaseURL: 'https://sos-community-app-default-rtdb.firebaseio.com',
    storageBucket: 'sos-community-app.appspot.com',
    iosBundleId: 'com.example.sosCommunity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcCyh5DCKEGHmMpP-hxgtfsrJVtNtpw8A',
    appId: '1:19406723565:ios:41c663a15846f034f4afe4',
    messagingSenderId: '19406723565',
    projectId: 'sos-community-app',
    databaseURL: 'https://sos-community-app-default-rtdb.firebaseio.com',
    storageBucket: 'sos-community-app.appspot.com',
    iosBundleId: 'com.example.sosCommunity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8Web50cawSMo8bfb0bPJr2ajeyEfgO74',
    appId: '1:19406723565:web:39d83228ba02f086f4afe4',
    messagingSenderId: '19406723565',
    projectId: 'sos-community-app',
    authDomain: 'sos-community-app.firebaseapp.com',
    databaseURL: 'https://sos-community-app-default-rtdb.firebaseio.com',
    storageBucket: 'sos-community-app.appspot.com',
  );
}
